name: My Starter Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Alejoooooo $GITHUB_TOKEN Emma $PR_URL Add other actions to build,
          echo test, and deploy to your project.
        env:
          GITHUB_TOKEN: ${{ secrets.USER_PRUEBA }}
          PR_URL: ${{ github.event.pull_request.html_url }}  
    
  call-reusable-workflow:
      strategy:
        matrix:
          nodeversion: [14, 16, 18, 20]
      uses: ./.github/workflows/reusable-workflow.yml
      with:
        node: ${{ matrix.nodeversion }}
